services:
  crm-system:
    build:
      context: .
      dockerfile: Dockerfile
    image: crm-system:latest
    container_name: crm-system
    env_file: .env
    restart: unless_stopped
    ports:
      - "5000:3000"
    depends_on:
      crm-database:
        condition: service_healthy

  crm-database:
    image: postgres:16-alpine
    container_name: crm-database
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_DB}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - crm_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8.0-alpine
    container_name: redis-cache
    restart: unless-stopped
    command: ["redis-server", "--requirepass", "${REDIS_PASS}"]
    ports:
      - "6379:6379"
    volumes:
      - crm-cache:/data
    networks:
      - app-network



volumes:
  crm_db:
    name: crm-database
    driver: local
  crm-cache:
    name: crm-cache
    driver: local


networks:
  app-network:
    driver: bridge
