
apiVersion: v1
kind: Secret
metadata:
  name: crm-system-secret
type: Opaque
stringData:
  DATABASE_PASSWORD: "root"
  JWT_ACCESS_SECRET: "b1e5116e09be196291a1d524da5c84f6149eec3d703c3cc52b182f521f0ac475db344d9a1140e2c8bff1fa888b8f0784faf689879f055eb837ae2b5a9a89f4ce"
  JWT_ACCESS_EXPIRES_IN: "15m"
  JWT_REFRESH_SECRET: "c188b37cd360908a4a92c88ff3bd4aa0f2e2b1ba16bdf6851023597be4d53a2faca43259a187f8d75bc321b367b2d9c46a8a8ae9aed73ab4cd64f7d85131eb02"
  JWT_ACCESS_EXPIRES_IN: "15m"
  JWT_REFRESH_EXPIRES_IN: "7d"
  MAIL_USER: "martininjah@gmail.com"
  MAIL_PASS: "sstu alel lfjj rltg"
